[tool.mypy]
python_version = "3.9"
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True
plugins = ["sqlalchemy.ext.mypy.plugin", "pydantic.mypy"]

[tool.mypy.overrides]
module = [
    "fastapi_limiter.*",
    "fastapi_csrf_protect.*",
    "pyotp.*",
    "qrcode.*",
    "jose.*",
    "passlib.*",
    "structlog.*",
    "google.oauth2.*",
    "google.auth.transport.*",
    "redis.*",
]
ignore_missing_imports = True
